# version: '3.8'
#MongoDB 5.0+ requires a CPU with AVX support, => sử dụng image: mongo:4.4
services:
    db-mongo:
        image: mongo:8.0.4
        environment:
            MONGO_INITDB_ROOT_USERNAME:
            MONGO_INITDB_ROOT_PASSWORD:
        ports:
            - 27017:27017
        volumes:
            - mongodb:/data/db
        expose:
            - 27017

    be-nest:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - PORT=3010
            - NODE_ENV=production
            - MONGO_URL=mongodb://db-mongo:27017/nest # ✅ Sửa lại kết nối MongoDB
        expose:
            - 3010
        ports:
            - 3010:3010
        depends_on:
            - db-mongo # ✅ Đảm bảo MongoDB khởi động trước

volumes:
    mongodb:

        # docker compose -p nest-app up -d
